ALTER TABLE `Job`
MODIFY `jobType` ENUM(
  'FETCH_POSTS',
  'FETCH_COMMENTS',
  'FETCH_PROFILE',
  'CHECK_PROXY',
  'ACCOUNT_HEALTH',
  'GROUP_MODERATION',
  'KEYWORD_MONITOR',
  'WORKFLOW_BUILD',
  'FETCH_VIDEOS',
  'POST_GROUP',
  'NURTURE_ACCOUNT',
  'AUTO_LIKE',
  'AUTO_COMMENT'
) NOT NULL;
