ALTER TABLE `Account`
MODIFY `platform` ENUM('FACEBOOK', 'TIKTOK', 'SHOPEE', 'YOUTUBE', 'SYSTEM', 'DATA') NOT NULL;

ALTER TABLE `Job`
MODIFY `platform` ENUM('FACEBOOK', 'TIKTOK', 'SHOPEE', 'YOUTUBE', 'SYSTEM', 'DATA') NOT NULL;

ALTER TABLE `DataSnapshot`
MODIFY `sourcePlatform` ENUM('FACEBOOK', 'TIKTOK', 'SHOPEE', 'YOUTUBE', 'SYSTEM', 'DATA') NOT NULL;

ALTER TABLE `Job`
MODIFY `jobType` ENUM(
  'FETCH_POSTS',
  'FETCH_COMMENTS',
  'FETCH_PROFILE',
  'CHECK_PROXY',
  'ACCOUNT_HEALTH',
  'GROUP_MODERATION',
  'KEYWORD_MONITOR',
  'WORKFLOW_BUILD',
  'FETCH_VIDEOS',
  'POST_GROUP',
  'NURTURE_ACCOUNT',
  'AUTO_LIKE',
  'AUTO_COMMENT',
  'REUP_VIDEO',
  'SHOPEE_VIDEO_AFF',
  'SHOPEE_LINK_CONVERT',
  'AI_CONTENT',
  'MARKETPLACE_SCAN',
  'BULK_MSG',
  'AUTO_JOIN_GROUP',
  'AUTO_DM',
  'CHANGE_PASSWORD',
  'REG_ACCOUNT',
  'SHOPEE_TRENDING',
  'EXPORT_DATA',
  'STRESS_TEST',
  'CLEANUP'
) NOT NULL;
